### ISSUE TITLE
Integrate Gigabyte RGB Fusion

### ISSUE THREAD

**Issue by henryruhs** [henryruhs/chroma-feedback#110]
Library: https://github.com/liquidctl/liquidctl
Supported Devices: https://github.com/liquidctl/liquidctl#supported-devices

```
python3 -m liquidctl --match gigabyte set sync color fixed 0080ff
```

**Comment by redaxmedia** [comment]
I close this for the moment. My personal interest was related to https://github.com/liquidctl/liquidctl/issues/226 but I have no time to integrate it to be honest to myself.

**Comment by henryruhs** [comment]
Done
